image: node:12

stages:
  - build
  - deploy

.build:
  stage: build
  cache:
    key: always
    paths:
      - node_modules/
  before_script:
    - node -v
    - npm -v
    - npm install
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

.deploy:
  stage: deploy
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - which rsync || (apt-get update -y && apt-get install rsync -y)
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

build_staging:
  extends: .build
  environment: staging
  only:
    - develop
  script: 
    - node -v
    - node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --prod --configuration=qa --aot
  

deploy_staging:
  extends: .deploy
  only:
    - develop
  environment: staging
  script:
    - cd dist
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress . $SSH_USER@$SSH_HOST:/home/beautyup/qa-cms-frontend/dist
  when: manual


build_prod:
  extends: .build
  environment: production
  only:
    - master
  script: 
    - node -v
    - node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --prod

deploy_prod:
  extends: .deploy
  only:
    - master
  environment: production
  script:
    - cd dist
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress . $SSH_USER@$SSH_HOST:/home/beautyup/cms-frontend/dist
  when: manual
